nutz:
  application:
    name: processor

# 设备协议配置
protocol:
  # 是否启用
  enable: true
  # 加载解析包
  classes:
    - com.budwk.app.access.protocol.demo.DemoProtocol

# 设备数据处理配置
processor:
  # 是否启用
  enable: true

rocketmq:
  # 集群环境多个nameserver用;分割
  nameserver-address: 127.0.0.1:9876
  # 生产者组
  producer-group: processor_producer
  producer-timeout: 50
  consumer-thread-max: 100
  consumer-thread-min: 5

mongodb:
  url: mongodb://127.0.0.1:27017/test

redisson:
  # 集群/分片/主从等配置见 https://github.com/nutzam/nutzmore/tree/master/nutz-integration-redisson
  mode: single
  single:
    address: redis://127.0.0.1:6379
    #password: 123456
    database: 5

jdbc:
  url: jdbc:mysql://10.10.10.10:3306/budiot?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: "root"
  validationQuery: select 1
  maxActive: 30
  testWhileIdle: true
  connectionProperties: druid.stat.slowSqlMillis=2000
  defaultAutoCommit: true

log:
  color: true
  level: debug
