nutz:
  application:
    name: gateway

# 设备协议配置
protocol:
  # 加载包名
  classes:
    - com.budwk.app.access.protocol.demo.DemoProtocol

rocketmq:
  # 集群环境多个nameserver用;分割
  nameserver-address: 127.0.0.1:9876
  # 生产者组
  producer-group: processor_producer
  producer-timeout: 50
  consumer-thread-max: 300
  consumer-thread-min: 10

redisson:
  # 集群/分片/主从等配置见 https://github.com/nutzam/nutzmore/tree/master/nutz-integration-redisson
  mode: single
  single:
    address: redis://127.0.0.1:6379
    #password: 123456
    database: 5

log:
  color: true
  level: debug
