wk:
  dao:
    tenant:
      enabled: true
      ignore-tables: []
    interceptor:
      log:
        enabled: false
      time:
        enabled: false
    sqls:
      path: sqls/
    druid-web:
      enabled: false
      username: admin
      password: admin
  database:
    enabled: true
    snowflake: true
    table:
      create: true
      migration: true
      add: true
      delete: false
      check: false
      package:
        - com.budwk.sp
  web:
    exception:
      exposeMessage: false
    log:
      enabled: true
      slowThreshold: 1000
  file:
    default-storage: LOCAL
    max-upload-size: 512000
    local:
      base-dir: ${user.home}/budiot/upload
    ftp:
      base-dir: /budiot/upload
    minio:
      bucket: budiot
      base-dir: upload

spring:
  main:
    allow-circular-references: true
  profiles:
    active: @spring.profile@
  application:
    name: wk-file
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

sa-token:
  token-name: Authorization
  timeout: 86400
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: random-64
  is-log: true
  is-read-header: true
  is-read-cookie: false
  is-print: false

server:
  port: 0

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log

fdfs:
  so-timeout: ${wk.file.fdfs.network-timeout}
  connect-timeout: ${wk.file.fdfs.connect-timeout}
  tracker-list: ${wk.file.fdfs.tracker-servers:}
