server:
  port: 9003

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: et922
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "wk:filecache:"
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.10.3:8848
        namespace: dev
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        metadata:
          version: v1.0
          framework: spring-boot-4
      config:
        server-addr: 10.10.10.3:8848
        namespace: dev
        group: DEFAULT_GROUP
        file-extension: yaml
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yaml?refreshEnabled=true

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
    register-mode: interface
  registry:
    address: nacos://10.10.10.3:8848
    parameters:
      namespace: dev
      group: DEFAULT_GROUP
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: -1
    threads: 200
  scan:
    base-packages: com.budwk.sp
  consumer:
    check: false
    timeout: 3000
    retries: 0
  provider:
    timeout: 3000
    retries: 0

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  scalar:
    enabled: true
    path: /scalar
  group-configs:
    - group: 'file'
      paths-to-match: /file/**, /pub/file/**

wk:
  # Dao层配置
  dao:
    # 打印SQL语句和执行时间
    interceptor:
      log:
        enabled: true
      time:
        enabled: true
    sqls:
      path: sqls/
    # Druid 监控密码配置
    druid-web:
      enabled: true
      username: admin
      password: admin
  # 数据库自动建表配置
  database:
    enabled: true
    snowflake: true
    table:
      create: true #是否自动建表 默认false
      migration: true #是否自动变更 默认false
      add: true # 是否添加列 默认false
      delete: false # 是否删除列 默认false
      check: false # 是否检查索引 默认false
      package: # 相关实体所在包
        - com.budwk.sp
  file:
    default-storage: LOCAL
    max-upload-size: 512000
    local:
      base-dir: ${user.home}/budiot/upload
    ftp:
      base-dir: /budiot/upload
    minio:
      bucket: budiot
      base-dir: upload

jdbc:
  url: jdbc:postgresql://localhost:5432/budiot?user=postgres&password=U/dH5RqdqvEXkmqoLjT4zSOIMnKaLLpST6yvETwTHtbWuWnKLRJtja6Mv60OerKDJ58aNXLIvfLUbrgdye2nfw==
  driver-class-name: org.postgresql.Driver
  initial-size: 5
  max-active: 20
  min-idle: 5
  max-wait: 60000
  pool-prepared-statements: true
  filters: config,stat,wall
  connection-properties: "config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI5l6A1HKfQsuqtiFTVTt3eXm8eP8LIiHbEixpaZYnhfBOVRC4wJJGRHmMZgFnltdmaJ+nasfZy79AbOmNjdoi0CAwEAAQ=="

logging:
  level:
    com.budwk.sp: DEBUG
    org.nutz.dao: DEBUG
