wk:
  dao:
    tenant:
      enabled: false
      ignore-tables: []
    interceptor:
      log:
        enabled: false
      time:
        enabled: false
    sqls:
      path: sqls/
    druid-web:
      enabled: false
      username: admin
      password: admin
  database:
    enabled: true
    snowflake: true
    table:
      create: true
      migration: true
      add: true
      delete: false
      check: false
      package:
        - com.budwk.sp
  device:
    message:
      enabled: true
      provider: REDIS
      topic-prefix: wk.device
      send-timeout: 3000
    handler:
      raw-topic: wk.device.uplink.raw
      script-timeout-ms: 1500
      script-refresh-channel: wk:device:protocol:script:refresh

spring:
  main:
    allow-circular-references: true
    web-application-type: none
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false
    nacos:
      discovery:
        register-enabled: false
  profiles:
    active: @spring.profile@
  application:
    name: wk-device-handler


logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log
