/*QUARTZ_1*/
DROP TABLE IF EXISTS SYS_QRTZ_FIRED_TRIGGERS;
/*QUARTZ_2*/
DROP TABLE IF EXISTS SYS_QRTZ_PAUSED_TRIGGER_GRPS;
/*QUARTZ_3*/
DROP TABLE IF EXISTS SYS_QRTZ_SCHEDULER_STATE;
/*QUARTZ_4*/
DROP TABLE IF EXISTS SYS_QRTZ_LOCKS;
/*QUARTZ_5*/
DROP TABLE IF EXISTS SYS_QRTZ_SIMPLE_TRIGGERS;
/*QUARTZ_6*/
DROP TABLE IF EXISTS SYS_QRTZ_CRON_TRIGGERS;
/*QUARTZ_7*/
DROP TABLE IF EXISTS SYS_QRTZ_SIMPROP_TRIGGERS;
/*QUARTZ_8*/
DROP TABLE IF EXISTS SYS_QRTZ_BLOB_TRIGGERS;
/*QUARTZ_9*/
DROP TABLE IF EXISTS SYS_QRTZ_TRIGGERS;
/*QUARTZ_10*/
DROP TABLE IF EXISTS SYS_QRTZ_JOB_DETAILS;
/*QUARTZ_11*/
DROP TABLE IF EXISTS SYS_QRTZ_CALENDARS;
/*QUARTZ_12*/
CREATE TABLE SYS_QRTZ_JOB_DETAILS ( SCHED_NAME VARCHAR(120) NOT NULL, JOB_NAME VARCHAR(200) NOT NULL, JOB_GROUP VARCHAR(200) NOT NULL, DESCRIPTION VARCHAR(250) NULL, JOB_CLASS_NAME VARCHAR(250) NOT NULL, IS_DURABLE BOOL NOT NULL, IS_NONCONCURRENT BOOL NOT NULL, IS_UPDATE_DATA BOOL NOT NULL, REQUESTS_RECOVERY BOOL NOT NULL, JOB_DATA BYTEA NULL, PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP) );
/*QUARTZ_13*/
CREATE TABLE SYS_QRTZ_TRIGGERS ( SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(200) NOT NULL, TRIGGER_GROUP VARCHAR(200) NOT NULL, JOB_NAME VARCHAR(200) NOT NULL, JOB_GROUP VARCHAR(200) NOT NULL, DESCRIPTION VARCHAR(250) NULL, NEXT_FIRE_TIME BIGINT NULL, PREV_FIRE_TIME BIGINT NULL, PRIORITY INTEGER NULL, TRIGGER_STATE VARCHAR(16) NOT NULL, TRIGGER_TYPE VARCHAR(8) NOT NULL, START_TIME BIGINT NOT NULL, END_TIME BIGINT NULL, CALENDAR_NAME VARCHAR(200) NULL, MISFIRE_INSTR SMALLINT NULL, JOB_DATA BYTEA NULL, PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP), FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP) REFERENCES SYS_QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP) );
/*QUARTZ_14*/
CREATE TABLE SYS_QRTZ_SIMPLE_TRIGGERS ( SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(200) NOT NULL, TRIGGER_GROUP VARCHAR(200) NOT NULL, REPEAT_COUNT BIGINT NOT NULL, REPEAT_INTERVAL BIGINT NOT NULL, TIMES_TRIGGERED BIGINT NOT NULL, PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP), FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES SYS_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) );
/*QUARTZ_15*/
CREATE TABLE SYS_QRTZ_CRON_TRIGGERS ( SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(200) NOT NULL, TRIGGER_GROUP VARCHAR(200) NOT NULL, CRON_EXPRESSION VARCHAR(120) NOT NULL, TIME_ZONE_ID VARCHAR(80), PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP), FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES SYS_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) );
/*QUARTZ_16*/
CREATE TABLE SYS_QRTZ_SIMPROP_TRIGGERS ( SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(200) NOT NULL, TRIGGER_GROUP VARCHAR(200) NOT NULL, STR_PROP_1 VARCHAR(512) NULL, STR_PROP_2 VARCHAR(512) NULL, STR_PROP_3 VARCHAR(512) NULL, INT_PROP_1 INT NULL, INT_PROP_2 INT NULL, LONG_PROP_1 BIGINT NULL, LONG_PROP_2 BIGINT NULL, DEC_PROP_1 NUMERIC(13, 4) NULL, DEC_PROP_2 NUMERIC(13, 4) NULL, BOOL_PROP_1 BOOL NULL, BOOL_PROP_2 BOOL NULL, PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP), FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES SYS_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) );
/*QUARTZ_17*/
CREATE TABLE SYS_QRTZ_BLOB_TRIGGERS ( SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(200) NOT NULL, TRIGGER_GROUP VARCHAR(200) NOT NULL, BLOB_DATA BYTEA NULL, PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP), FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES SYS_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) );
/*QUARTZ_18*/
CREATE TABLE SYS_QRTZ_CALENDARS ( SCHED_NAME VARCHAR(120) NOT NULL, CALENDAR_NAME VARCHAR(200) NOT NULL, CALENDAR BYTEA NOT NULL, PRIMARY KEY (SCHED_NAME, CALENDAR_NAME) );
/*QUARTZ_19*/
CREATE TABLE SYS_QRTZ_PAUSED_TRIGGER_GRPS ( SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_GROUP VARCHAR(200) NOT NULL, PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP) );
/*QUARTZ_20*/
CREATE TABLE SYS_QRTZ_FIRED_TRIGGERS ( SCHED_NAME VARCHAR(120) NOT NULL, ENTRY_ID VARCHAR(95) NOT NULL, TRIGGER_NAME VARCHAR(200) NOT NULL, TRIGGER_GROUP VARCHAR(200) NOT NULL, INSTANCE_NAME VARCHAR(200) NOT NULL, FIRED_TIME BIGINT NOT NULL, SCHED_TIME BIGINT NOT NULL, PRIORITY INTEGER NOT NULL, STATE VARCHAR(16) NOT NULL, JOB_NAME VARCHAR(200) NULL, JOB_GROUP VARCHAR(200) NULL, IS_NONCONCURRENT BOOL NULL, REQUESTS_RECOVERY BOOL NULL, PRIMARY KEY (SCHED_NAME, ENTRY_ID) );
/*QUARTZ_21*/
CREATE TABLE SYS_QRTZ_SCHEDULER_STATE ( SCHED_NAME VARCHAR(120) NOT NULL, INSTANCE_NAME VARCHAR(200) NOT NULL, LAST_CHECKIN_TIME BIGINT NOT NULL, CHECKIN_INTERVAL BIGINT NOT NULL, PRIMARY KEY (SCHED_NAME, INSTANCE_NAME) );
/*QUARTZ_22*/
CREATE TABLE SYS_QRTZ_LOCKS ( SCHED_NAME VARCHAR(120) NOT NULL, LOCK_NAME VARCHAR(40) NOT NULL, PRIMARY KEY (SCHED_NAME, LOCK_NAME) );
/*QUARTZ_23*/
CREATE INDEX IDX_QRTZ_J_REQ_RECOVERY ON SYS_QRTZ_JOB_DETAILS (SCHED_NAME, REQUESTS_RECOVERY);
/*QUARTZ_24*/
CREATE INDEX IDX_QRTZ_J_GRP ON SYS_QRTZ_JOB_DETAILS (SCHED_NAME, JOB_GROUP);
/*QUARTZ_25*/
CREATE INDEX IDX_QRTZ_T_J ON SYS_QRTZ_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP);
/*QUARTZ_26*/
CREATE INDEX IDX_QRTZ_T_JG ON SYS_QRTZ_TRIGGERS (SCHED_NAME, JOB_GROUP);
/*QUARTZ_27*/
CREATE INDEX IDX_QRTZ_T_C ON SYS_QRTZ_TRIGGERS (SCHED_NAME, CALENDAR_NAME);
/*QUARTZ_28*/
CREATE INDEX IDX_QRTZ_T_G ON SYS_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_GROUP);
/*QUARTZ_29*/
CREATE INDEX IDX_QRTZ_T_STATE ON SYS_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE);
/*QUARTZ_30*/
CREATE INDEX IDX_QRTZ_T_N_STATE ON SYS_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE);
/*QUARTZ_31*/
CREATE INDEX IDX_QRTZ_T_N_G_STATE ON SYS_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE);
/*QUARTZ_32*/
CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON SYS_QRTZ_TRIGGERS (SCHED_NAME, NEXT_FIRE_TIME);
/*QUARTZ_33*/
CREATE INDEX IDX_QRTZ_T_NFT_ST ON SYS_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME);
/*QUARTZ_34*/
CREATE INDEX IDX_QRTZ_T_NFT_MISFIRE ON SYS_QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME);
/*QUARTZ_35*/
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE ON SYS_QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE);
/*QUARTZ_36*/
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE_GRP ON SYS_QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE);
/*QUARTZ_37*/
CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME ON SYS_QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME);
/*QUARTZ_38*/
CREATE INDEX IDX_QRTZ_FT_INST_JOB_REQ_RCVRY ON SYS_QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY);
/*QUARTZ_39*/
CREATE INDEX IDX_QRTZ_FT_J_G ON SYS_QRTZ_FIRED_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP);
/*QUARTZ_40*/
CREATE INDEX IDX_QRTZ_FT_JG ON SYS_QRTZ_FIRED_TRIGGERS (SCHED_NAME, JOB_GROUP);
/*QUARTZ_41*/
CREATE INDEX IDX_QRTZ_FT_T_G ON SYS_QRTZ_FIRED_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);
/*QUARTZ_42*/
CREATE INDEX IDX_QRTZ_FT_TG ON SYS_QRTZ_FIRED_TRIGGERS (SCHED_NAME, TRIGGER_GROUP);
/*QUARTZ_43*/
COMMIT;