nutz:
  application:
    name: gateway
gateway:
  AEP_DEMO:
    # http 网关如果同一个jvm实例种配置的端口一致，那么将会复用相同的 HttpServer，默认的路由地址为 /网关id/接入平台/up
    transport: http
    protocol: AEP_DEMO
    properties:
      port: 9100
      # 是否启用ssl
      ssl: false
      # 证书地址
      # 接入的平台，默认值为 budiot
      platform: aep
      # 如果配置了path，那么将会使用这个作为路由。如果相同的HttpServer存在多个出现重复的path，只会第一个生效，其他的将会采用默认路由
      path: /aepdemo/aep/up
      # 是否等待响应。如果为 true，HttpServer 将不会立即返回响应，将会等待后续下发的响应信息
      waitResponse: false
      # 等待的超时时间，单位为秒。默认为30秒
      waitTimeout: 30

rocketmq:
  enable: false
  # 集群环境多个nameserver用;分割
  nameserver-address: 127.0.0.1:9876
  # 生产者组
  producer-group: gateway_producer
  producer-timeout: 1
  consumer-thread-max: 100
  consumer-thread-min: 5

rabbitmq:
  enable: true
  host: 192.168.6.67
  port: 5672
  username: admin
  password: '@#Pass123'
  thread:
    max: 8
    min: 4
  queue:
    size: 10000

message:
  transfer:
    # 消息发送者实例id，不设置则自动生成
    instanceId: '001'

log:
  color: true
  level: debug
